-- Schema for PostgreSQL

DROP TABLE IF EXISTS app_update CASCADE;
CREATE TABLE app_update (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version varchar(10),
    update_desc varchar(500),
    create_time timestamp,
    status smallint,
    grayscale_uid varchar(1000),
    file_type smallint,
    outer_link varchar(200),
    CONSTRAINT uq_app_update_version UNIQUE (version)
);

DROP TABLE IF EXISTS chat_message CASCADE;
CREATE TABLE chat_message (
    message_id bigserial PRIMARY KEY,
    session_id varchar(32) NOT NULL,
    message_type smallint NOT NULL,
    message_content varchar(500),
    send_user_id varchar(12),
    send_user_nick_name varchar(20),
    send_time bigint,
    contact_id varchar(12) NOT NULL,
    contact_type smallint,
    file_size bigint,
    file_name varchar(200),
    file_type smallint,
    status smallint DEFAULT 1
);
CREATE INDEX idx_chat_message_session_id ON chat_message(session_id);
CREATE INDEX idx_chat_message_send_user_id ON chat_message(send_user_id);
CREATE INDEX idx_chat_message_contact_id ON chat_message(contact_id);
CREATE INDEX idx_chat_message_send_time ON chat_message(send_time);

DROP TABLE IF EXISTS chat_session CASCADE;
CREATE TABLE chat_session (
    session_id varchar(32) PRIMARY KEY,
    last_message varchar(500),
    last_receive_time bigint
);

DROP TABLE IF EXISTS chat_session_user CASCADE;
CREATE TABLE chat_session_user (
    user_id varchar(12) NOT NULL,
    contact_id varchar(12) NOT NULL,
    session_id varchar(32) NOT NULL,
    contact_name varchar(20),
    PRIMARY KEY (user_id, contact_id)
);
CREATE INDEX idx_chat_session_user_user_id ON chat_session_user(user_id);
CREATE INDEX idx_chat_session_user_session_id ON chat_session_user(session_id);

DROP TABLE IF EXISTS group_info CASCADE;
CREATE TABLE group_info (
    group_id varchar(12) PRIMARY KEY,
    group_name varchar(20),
    group_owner_id varchar(12),
    create_time timestamp,
    group_notice varchar(500),
    join_type smallint,
    status smallint DEFAULT 1
);

DROP TABLE IF EXISTS user_contact CASCADE;
CREATE TABLE user_contact (
    user_id varchar(12) NOT NULL,
    contact_id varchar(12) NOT NULL,
    contact_type smallint,
    create_time timestamp,
    status smallint,
    last_update_time timestamp,
    PRIMARY KEY (user_id, contact_id)
);
CREATE INDEX idx_user_contact_contact_id ON user_contact(contact_id);

DROP TABLE IF EXISTS user_contact_apply CASCADE;
CREATE TABLE user_contact_apply (
    apply_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apply_user_id varchar(12) NOT NULL,
    receive_user_id varchar(12) NOT NULL,
    contact_type smallint NOT NULL,
    contact_id varchar(12),
    last_apply_time bigint,
    status smallint,
    apply_info varchar(100),
    CONSTRAINT uq_user_contact_apply UNIQUE (apply_user_id, receive_user_id, contact_id)
);
CREATE INDEX idx_user_contact_apply_last_time ON user_contact_apply(last_apply_time);

DROP TABLE IF EXISTS user_info CASCADE;
CREATE TABLE user_info (
    user_id varchar(12) PRIMARY KEY,
    email varchar(50) UNIQUE,
    nick_name varchar(20),
    join_type smallint,
    sex smallint,
    password varchar(32),
    personal_signature varchar(50),
    status smallint,
    create_time timestamp,
    last_login_time timestamp,
    area_name varchar(50),
    area_code varchar(50),
    last_off_time bigint
);

DROP TABLE IF EXISTS user_info_beauty CASCADE;
CREATE TABLE user_info_beauty (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(50) NOT NULL,
    user_id varchar(12) NOT NULL,
    status smallint DEFAULT 0,
    CONSTRAINT uq_user_info_beauty_user_id UNIQUE (user_id),
    CONSTRAINT uq_user_info_beauty_email UNIQUE (email)
);
